format_list:
    breakpoint: 16
    elementos:
    -   x: 1
        y: 2
    -   x: 3
        y: 4
    - &id001
        x: 5
        y: 6
    estagio: loop
    l: *id001
    r: 11
soma:
    breakpoint: 5
    x: 5
    y: 6
