formata_resposta:
    caracteres:
    -   caracter: .
        posicao: 3
    -   caracter: .
        posicao: 7
    -   caracter: '-'
        posicao: 11
    elemento: N
    idx: 13
    input: '123456789'
    letras_input:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    letras_padrao:
    - N
    - N
    - N
    - N
    - N
    - N
    - N
    - N
    - N
    - N
    - N
    padrao: NNN.NNN.NNN-NN
line: 20
